spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    #force data.sql script execution
    initialization-mode: always

logging:
  level:
    org.spring.framework.web : debug